version: 1
formatters:
  simple:
    format: '[%(asctime)s %(levelname)s]  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
loggers:
  araap:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]